### ISSUE TITLE
panic when not defining RequestContext middleware

### ISSUE THREAD

**Issue by jon-walton** [vektah/gqlgen#102]
Hello,

We allow incoming gql requests over the gqlgen http handler as well as an internal grpc endpoint. Below is a barebones representation of the grpc handler

```golang
	doc, _ := query.Parse(r.Query)
	validation.Validate(c.exec.Schema(), doc)
	op, _ := doc.GetOperation(r.Operation)

	ctx = graphql.WithRequestContext(ctx, &graphql.RequestContext{
		Variables:          variables,
	})

	c.exec.Query(ctx, op))
```

followed by the query code in our `generated.go`

```golang
func (e *executableSchema) Query(ctx context.Context, op *query.Operation) *graphql.Response {
	ec := executionContext{graphql.GetRequestContext(ctx), e.resolvers}

	buf := ec.RequestMiddleware(ctx, func(ctx context.Context) []byte {
		data := ec._Query(ctx, op.Selections)
		var buf bytes.Buffer
		data.MarshalGQL(&buf)
		return buf.Bytes()
	})

	return &graphql.Response{
		Data:   buf,
		Errors: ec.Errors,
	}
}
```

Creating the RequestContext like so

```golang
	noopResolverMiddleware := func(ctx context.Context, next graphql.Resolver) (res interface{}, err error) {
		return next(ctx)
	}

	noopRequestMiddleware := func(ctx context.Context, next func(ctx context.Context) []byte) []byte {
		return next(ctx)
	}

	ctx = graphql.WithRequestContext(ctx, &graphql.RequestContext{
		Doc:                doc,
		RawQuery:           r.Query,
		Variables:          variables,
		Recover:            graphql.DefaultRecoverFunc,
		ResolverMiddleware: noopResolverMiddleware,
		RequestMiddleware:  noopRequestMiddleware,
		ErrorBuilder: graphql.ErrorBuilder{
			ErrorPresenter: graphql.DefaultErrorPresenter,
		},
	})
```
resolves the panic.

I'm not sure what path you want to take, either having a DefaultRequestContext or generate code that checks for nil on the resolvers (i haven't tested if it panics when ErrorBuilder or Recover are nil).

### Expected Behaviour
don't panic!

### Actual Behavior
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd39bdc]

goroutine 252 [running]:
gitlab.com/xxx/backend/dashboard/internal/graph.(*executableSchema).Query(0xc4202d0da0, 0x12a2ca0, 0xc420154d50, 0xc4207941b0, 0xc420154d50)
    /go/src/gitlab.com/xxx/backend/dashboard/internal/graph/generated.go:145 +0xec
gitlab.com/xxx/backend/dashboard/internal/grpc.(*CTX).GraphQLWithAuth(0xc4207aa960, 0x7fb3ce9d5f88, 0xc420154d50, 0xc4202362d0, 0xc4207aa960, 0x1294840, 0xc420918040)
    /go/src/gitlab.com/xxx/backend/dashboard/internal/grpc/graphql.go:60 +0x4a9
gitlab.com/xxx/backend/pb._Dashboard_GraphQLWithAuth_Handler.func1(0x7fb3ce9d5f88, 0xc4207aa780, 0x1080260, 0xc4202362d0, 0x1169650, 0x24, 0x7fb3ce9d5f88, 0xc4207aa780)
    /go/src/gitlab.com/xxx/backend/pb/dashboard.pb.go:103 +0x86
gitlab.com/xxx/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x7fb3ce9d5f88, 0xc4207aa450, 0x1080260, 0xc4202362d0, 0xc42010a3a0, 0xc42010a440, 0x1169651, 0x13, 0x1169665, 0xf)
    /go/src/gitlab.com/xxx/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing/server_interceptors.go:30 +0xda
gitlab.com/xxx/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1.1(0x7fb3ce9d5f88, 0xc4207aa450, 0x1080260, 0xc4202362d0, 0x24, 0xc420236410, 0xc420486000, 0x10)
    /go/src/gitlab.com/xxx/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x66
gitlab.com/xxx/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x7fb3ce9d5f88, 0xc4207aa450, 0x1080260, 0xc4202362d0, 0xc42010a3a0, 0xc42010a460, 0x902eea, 0x10691a0, 0xc42010a480, 0xc42010a3a0)
    /go/src/gitlab.com/xxx/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:86 +0xad
gitlab.com/xxx/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1.1(0x7fb3ce9d5f88, 0xc4207aa450, 0x1080260, 0xc4202362d0, 0x7fb3ce9d5f88, 0xc4207999f8, 0x4108c8, 0x20)
    /go/src/gitlab.com/xxx/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x66
gitlab.com/xxx/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2(0x7fb3ce9d5f88, 0xc4207aa450, 0x1080260, 0xc4202362d0, 0xc42010a3a0, 0xc42010a440, 0xfb3240, 0x198dea8, 0x1100300, 0xc420570f00)
    /go/src/gitlab.com/xxx/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:38 +0xf6
gitlab.com/xxx/backend/pb._Dashboard_GraphQLWithAuth_Handler(0xf88400, 0xc4207aa960, 0x7fb3ce9d5f88, 0xc4207aa450, 0xc4203c8150, 0xc420249060, 0x0, 0x0, 0x300000002, 0xc420a5ed80)
    /go/src/gitlab.com/xxx/backend/pb/dashboard.pb.go:105 +0x167
gitlab.com/xxx/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420948420, 0x12a76a0, 0xc42006bb00, 0xc420570f00, 0xc4207aa9f0, 0x1957da0, 0x0, 0x0, 0x0)
    /go/src/gitlab.com/xxx/vendor/google.golang.org/grpc/server.go:923 +0x889
gitlab.com/xxx/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420948420, 0x12a76a0, 0xc42006bb00, 0xc420570f00, 0x0)
    /go/src/gitlab.com/xxx/vendor/google.golang.org/grpc/server.go:1148 +0x1318
gitlab.com/xxx/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420040120, 0xc420948420, 0x12a76a0, 0xc42006bb00, 0xc420570f00)
    /go/src/gitlab.com/xxx/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by gitlab.com/xxx/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    /go/src/gitlab.com/xxx/vendor/google.golang.org/grpc/server.go:635 +0xa1```

### Minimal graphql.schema and models to reproduce
N/A

**Comment by vektah** [comment]
Thats super interesting. I know a few people are going graphql over grpc but I wasn't expecting anyone to be doing it yet. Those APIs are still subject to a bit of churn, but as long as your ok with keeping up with the API it should be fine. 

Maybe the best bet is to clean up that internal API a little and add the same option pattern use by the handler. Thoughts?
