### ISSUE TITLE
Json unable to marshal response

### ISSUE THREAD

**Issue by Teddy-Schmitz** [vektah/gqlgen#121]
### Expected Behaviour
Response is returned normally
### Actual Behavior
gqlgen panics with a json unmarshal error on version `ab6e65bd7d3b9dec26340074435cffec27cfe8d8`.  On latest version it panics with a nil pointer exception

Stacktrace for the 2 versions here.

```
json: error calling MarshalJSON for type json.RawMessage: invalid character 'U' in string escape code

goroutine 6 [running]:
runtime/debug.Stack(0x1, 0x0, 0x0)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/graphql.DefaultRecoverFunc(0x81f760, 0xc420095e00, 0x75ea20, 0xc42010adc0, 0x199, 0xc420090100)
	/home/teddy/go/src/gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/graphql/recovery.go:16 +0xa7
gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler.GraphQL.func3.1(0xc420120770, 0x81f760, 0xc420095e00, 0x81f420, 0xc4201dc000)
	/home/teddy/go/src/gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler/graphql.go:185 +0x73
panic(0x75ea20, 0xc42010adc0)
	/usr/lib/go/src/runtime/panic.go:502 +0x229
gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler.GraphQL.func3(0x81f420, 0xc4201dc000, 0xc420160300)
	/home/teddy/go/src/gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler/graphql.go:194 +0xcbf
net/http.HandlerFunc.ServeHTTP(0xc42010aac0, 0x81f420, 0xc4201dc000, 0xc420160300)
	/usr/lib/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0x9e7fa0, 0x81f420, 0xc4201dc000, 0xc420160300)
	/usr/lib/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc42009d450, 0x81f420, 0xc4201dc000, 0xc420160300)
	/usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc42009ed20, 0x81f6a0, 0xc420022c00)
	/usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2795 +0x27b

```

Current Master
```
2018/05/30 11:42:00 http: panic serving [::1]:50678: runtime error: invalid memory address or nil pointer dereference
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc4200a4c80)
	/usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x768780, 0x9d89f0)
	/usr/lib/go/src/runtime/panic.go:502 +0x229
gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler.GraphQL.func1.1(0xc420136770, 0x81f7a0, 0xc420206690, 0x81f460, 0xc4202001c0)
	/home/teddy/go/src/gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler/graphql.go:182 +0x6e
panic(0x75ea00, 0xc42011f7e0)
	/usr/lib/go/src/runtime/panic.go:502 +0x229
gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler.GraphQL.func1(0x81f460, 0xc4202001c0, 0xc42017a400)
	/home/teddy/go/src/gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler/graphql.go:191 +0xb9a
net/http.HandlerFunc.ServeHTTP(0xc42011ea60, 0x81f460, 0xc4202001c0, 0xc42017a400)
	/usr/lib/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0x9e7fa0, 0x81f460, 0xc4202001c0, 0xc42017a400)
	/usr/lib/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4200a3450, 0x81f460, 0xc4202001c0, 0xc42017a400)
	/usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4200a4c80, 0x81f6e0, 0xc4200b6b80)
	/usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2795 +0x27b
2018/05/30 11:42:00 http: panic serving [::1]:50690: runtime error: invalid memory address or nil pointer dereference
goroutine 4 [running]:
net/http.(*conn).serve.func1(0xc4203d4000)
	/usr/lib/go/src/net/http/server.go:1726 +0xd0
panic(0x768780, 0x9d89f0)
	/usr/lib/go/src/runtime/panic.go:502 +0x229
gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler.GraphQL.func1.1(0xc420136770, 0x81f7a0, 0xc4201f45d0, 0x81f460, 0xc4203de000)
	/home/teddy/go/src/gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler/graphql.go:182 +0x6e
panic(0x75ea00, 0xc42000c1a0)
	/usr/lib/go/src/runtime/panic.go:502 +0x229
gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler.GraphQL.func1(0x81f460, 0xc4203de000, 0xc4201fa100)
	/home/teddy/go/src/gitlab.com/teddy-schmitz/gqlPanic/vendor/github.com/vektah/gqlgen/handler/graphql.go:191 +0xb9a
net/http.HandlerFunc.ServeHTTP(0xc42011ea60, 0x81f460, 0xc4203de000, 0xc4201fa100)
	/usr/lib/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0x9e7fa0, 0x81f460, 0xc4203de000, 0xc4201fa100)
	/usr/lib/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4200a3450, 0x81f460, 0xc4203de000, 0xc4201fa100)
	/usr/lib/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4203d4000, 0x81f6e0, 0xc420022100)
	/usr/lib/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2795 +0x27b
```

Using go 1.10.2
### Minimal graphql.schema and models to reproduce
```
schema {
    query: Query
}

type Query {
    Test(): Panic
}

type Panic {
    name: String!
}
```
Return the string "\U000fe4ed"

Example repo,

https://github.com/Teddy-Schmitz/gqlPanic

**Comment by rsergeychik** [comment]
Also quite similar error can be encountered when attempting to write golang's float NaN to float json field
