### ISSUE TITLE
panic from generate

### ISSUE THREAD

**Issue by buchanae** [vektah/gqlgen#40]
```
gqlgen -out generated.go -package graphql
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x121635f]

goroutine 1 [running]:
github.com/vektah/gqlgen/codegen.Bind(0xc420116af0, 0xc420140bd0, 0xc424bb6280, 0x3b, 0x1, 0xc4230de660, 0xb)
	/Users/buchanae/src/github.com/vektah/gqlgen/codegen/build.go:87 +0x45f
main.main()
	/Users/buchanae/src/github.com/vektah/gqlgen/main.go:75 +0x3d6
```

schema
```
scalar Time

type Workflow {
  id: ID!
  inputs: [WorkflowInput!]!
  outputs: [WorkflowOutput!]!
  steps: [Step!]!
  runs: [WorkflowRun!]!
}

type WorkflowInput {
  id :ID!
}

type WorkflowOutput {
  id :ID!
}

type Step {
  id :ID!
  name: String!
  inputs: [StepInput!]!
  outputs: [StepOutput!]!
  order: Int!
  workflow: Workflow!
}

type StepInput {
  id :ID!
}

type StepOutput {
  id :ID!
}

enum RunState {
  Complete
  Running
  Error
  Idle
}

type WorkflowRun {
  id :ID!
  total: Int!
  idle: Int!
  running: Int!
  error: Int!
  complete: Int!

  state: RunState!
  done: Boolean!

  startTime: Time
  endTime: Time

  workflow: Workflow!
  stepRuns: [StepRun!]!
}

type StepRun {
  id :ID!

  state: RunState!
  task: Task!
  step: Step!
}

enum TaskState {
  Unknown
  Queued
  Initializing
  Running
  ExecutorError
  SystemError
  Complete
}

type Task {
  id :ID!
  state: TaskState!
}
```

**Comment by buchanae** [comment]
I was missing the `schema` and `type Query`
